services:
  debezium:
    image: yugabytedb/debezium-server:1.7.0-yb-4t-1
    container_name: debezium-server
    ports:
      - 8080:8080
    environment:
      DEBEZIUM_SINK_TYPE: kafka
      DEBEZIUM_SINK_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: ${KAFKA_HOST}
      DEBEZIUM_SINK_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      DEBEZIUM_SINK_KAFKA_PRODUCER_VALUE_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      DEBEZIUM_SOURCE_CONNECTOR_CLASS: io.debezium.connector.yugabytedb.YugabyteDBConnector
      DEBEZIUM_SOURCE_OFFSET_STORAGE_FILE_FILENAME: data/offsets.dat
      DEBEZIUM_SOURCE_OFFSET_FLUSH_INTERVAL_MS: 0
      DEBEZIUM_SOURCE_DATABASE_HOSTNAME: ${PGHOST}
      DEBEZIUM_SOURCE_DATABASE_PORT: 5433
      DEBEZIUM_SOURCE_DATABASE_USER: yugabyte
      DEBEZIUM_SOURCE_DATABASE_PASSWORD: yugabyte
      DEBEZIUM_SOURCE_DATABASE_DBNAME: yugabyte
      DEBEZIUM_SOURCE_DATABASE_SERVER_NAME: dbserver1
      DEBEZIUM_SOURCE_DATABASE_STREAMID: ${CDC_SDK_STREAM_ID}
      DEBEZIUM_SOURCE_TABLE_INCLUDE_LIST: ${TABLES}
      DEBEZIUM_SOURCE_DATABASE_MASTER_ADDRESSES: ${MASTER_ADDRESSES}
      DEBEZIUM_SOURCE_SNAPSHOT_MODE: never
    volumes:
      - $PWD/volumes/debezium/data:/debezium/data


